module.exports = {
  'ant-prefix': 'ant',
  'primary-color': '#259DDB',
  'info-color': '#259DDB',
  'success-color': '#22B400',
  'error-color': '#CC282B',
  'warning-color': '#FB8305',
  'font-size-base': '14px',
  'border-radius-base': '4px',
  'layout-header-background': '#1B1E24',
  'layout-sider-background': '#1B1E24',
  'avatar-size-base': '36px',
  'avatar-size-lg': '58px',
  'avatar-size-sm': '28px',
  'avatar-bg': '#4e6086',
  'avatar-color': '#fff',
  'menu-collapsed-width': '64px',
  'menu-item-height': '40px',
  'menu-item-color': '#6e7380',
  'menu-dark-submenu-bg': '#1B1E24',
  'menu-inline-toplevel-item-height': '50px',
  'menu-item-active-bg': '#259DDB',
  'menu-item-active-border-width': '0',
  'border-color-split': '#f3f3f3',
  'box-shadow-base': '0 2px 4px 0 rgba(0,0,0,0.32)',
  'heading-color': '#565656',
  'text-color': '#858585',
  'disabled-color': '#acacac',
  'layout-body-background': '#f2f2f2',
  'border-color-base': '#ebebeb',
  'table-header-bg': 'transparent',
  'table-selected-row-bg': '#fff2dc',
  'table-row-hover-bg': '#e7f3ff',
  'btn-padding-base': '0 10px',
  'btn-padding-lg': '0 14px',
  'btn-padding-sm': '0 10px',
  'btn-default-color': 'rgba(0,0,0, 0.65)',
  'btn-default-border': '#D9D9D9',
  'btn-disable-color': '#B8B8B8',
  'btn-disable-bg': 'rgba(0,0,0,0.04)',
  'btn-disable-border': '#D9D9D9',
  'label-color': '#333',
  'input-border-color': '#d9d9d9',
  'form-item-margin-bottom': '-8px',
  'tree-directory-selected-bg': 'rgba(37,157,219,0.4)',
};
