export const FILTER_TYPE = {
  INPUT: 'INPUT',
  SELECT: 'SELECT',
  MULTIPLE_SELECT: 'MULTIPLE_SELECT',
  DATE_PICKER: 'DATE_PICKER',
  RANGE_PICKER: 'RANGE_PICKER',
};

export const SELECT_TYPE_LIST = [FILTER_TYPE.SELECT, FILTER_TYPE.MULTIPLE_SELECT];

export const EXTRA_FILTER_TYPE = {
  MULTIPLE_SELECT_THEME_PARK_CODE: `${FILTER_TYPE.MULTIPLE_SELECT}_themeParkCode`,
  MULTIPLE_SELECT_AGE_GROUP: `${FILTER_TYPE.MULTIPLE_SELECT}_ageGroup`,
  MULTIPLE_SELECT_CHANNEL: `${FILTER_TYPE.MULTIPLE_SELECT}_channel`,
  MULTIPLE_SELECT_CUSTOMER_NAME: `${FILTER_TYPE.MULTIPLE_SELECT}_customerName`,
};
