/* eslint-disable */
import UAAService from '@/uaa-npm';

export async function queryAllMenus(params) {
  return UAAService.request(`/b2b/user/v1/menu/queryMenuTree?appCode=${params.appCode}`, {
    method: 'GET',
  });
}

export async function addMenu(params) {
  return UAAService.request(`/b2b/user/v1/menu/addMenu`, {
    method: 'POST',
    body: {
      ...params,
    },
  });
}

export async function modifyMenu(params) {
  return UAAService.request(`/b2b/user/v1/menu/modifyMenu`, {
    method: 'POST',
    body: {
      ...params,
    },
  });
}

export async function removeMenu(params) {
  return UAAService.request(`/b2b/user/v1/menu/removeMenu`, {
    method: 'POST',
    body: {
      ...params,
    },
  });
}

export async function moveUpMenu(params) {
  return UAAService.request(`/b2b/user/v1/menu/operateMoveUpMenu`, {
    method: 'POST',
    body: {
      ...params,
    },
  });
}

export async function moveDownMenu(params) {
  return UAAService.request(`/b2b/user/v1/menu/operateMoveDownMenu`, {
    method: 'POST',
    body: {
      ...params,
    },
  });
}

export function queryAllFontIcons() {
  return {
    success: '0',
    errorMsg: '',
    data: [
      {
        page: 1,
        list: [
          'account-book',
          'alert',
          'api',
          'appstore',
          'audio',
          'bank',
          'bell',
          'book',
          'bug',
          'bulb',
          'calculator',
          'build',
          'calendar',
          'camera',
          'car',
          'carry-out',
          'cloud',
          'code',
          'compass',
          'contacts',
          'container',
          'control',
          'credit-card',
          'crown',
          'customer-service',
          'dashboard',
          'database',
          'dislike',
          'environment',
          'experiment',
          'eye-invisible',
          'eye',
          'file-add',
          'file-excel',
          'file-exclamation',
          'file-image',
          'file-markdown',
          'file-pdf',
          'file-ppt',
          'file-text',
          'file-unknown',
          'file-word',
          'file-zip',
          'file',
          'filter',
        ],
      },
      {
        page: 2,
        list: [
          'fire',
          'flag',
          'folder-add',
          'folder',
          'folder-open',
          'frown',
          'funnel-plot',
          'gift',
          'hdd',
          'heart',
          'home',
          'hourglass',
          'idcard',
          'insurance',
          'interaction',
          'layout',
          'like',
          'lock',
          'mail',
          'medicine-box',
          'meh',
          'message',
          'mobile',
          'money-collect',
          'pay-circle',
          'notification',
          'phone',
          'picture',
          'play-square',
          'printer',
          'profile',
          'project',
          'pushpin',
          'property-safety',
          'read',
          'reconciliation',
          'red-envelope',
          'rest',
          'rocket',
          'safety-certificate',
          'save',
          'schedule',
          'security-scan',
          'setting',
          'shop',
        ],
      },
      {
        page: 3,
        list: [
          'smile',
          'sound',
          'star',
          'switcher',
          'tablet',
          'tag',
          'tags',
          'tool',
          'thunderbolt',
          'trophy',
          'unlock',
          'usb',
          'video-camera',
          'wallet',
          'apartment',
          'audit',
          'barcode',
          'bars',
          'block',
          'border',
          'branches',
          'ci',
          'cloud-download',
          'cloud-server',
          'cloud-sync',
          'cloud-upload',
          'cluster',
          'coffee',
          'copyright',
          'deployment-unit',
          'desktop',
          'disconnect',
          'dollar',
          'download',
          'ellipsis',
          'euro',
          'exception',
          'export',
          'file-done',
          'file-jpg',
          'file-protect',
          'file-sync',
          'file-search',
          'shopping',
        ],
      },
      {
        page: 4,
        list: [
          'fork',
          'gateway',
          'global',
          'gold',
          'history',
          'import',
          'inbox',
          'key',
          'laptop',
          'link',
          'line',
          'loading-3-quarters',
          'loading',
          'man',
          'menu',
          'monitor',
          'more',
          'number',
          'percentage',
          'paper-clip',
          'pound',
          'poweroff',
          'pull-request',
          'qrcode',
          'copyright',
          'deployment-unit',
          'desktop',
          'disconnect',
          'dollar',
          'download',
          'ellipsis',
          'euro',
          'exception',
          'export',
          'file-done',
          'file-jpg',
          'file-protect',
          'file-sync',
          'file-search',
          'fork',
          'gateway',
          'global',
          'gold',
          'skin',
        ],
      },
      {
        page: 5,
        list: [
          'history',
          'import',
          'inbox',
          'key',
          'laptop',
          'link',
          'line',
          'loading-3-quarters',
          'loading',
          'man',
          'menu',
          'monitor',
          'more',
          'number',
          'percentage',
          'paper-clip',
          'pound',
          'poweroff',
          'pull-request',
          'qrcode',
          'reload',
          'safety',
          'robot',
          'scan',
          'search',
          'select',
          'shake',
          'share-alt',
          'shopping-cart',
          'solution',
          'sync',
          'table',
          'team',
          'to-top',
          'trademark',
          'transaction',
          'upload',
          'user-add',
          'user-delete',
          'usergroup-add',
          'user',
          'usergroup-delete',
          'wifi',
          'woman',
          'sliders',
        ],
      },
      {
        page: 6,
        list: [
          'area-chart',
          'pie-chart',
          'bar-chart',
          'dot-chart',
          'line-chart',
          'radar-chart',
          'heat-map',
          'fall',
          'rise',
          'stock',
          'box-plot',
          'fund',
          'icon-addteam-copy',
          'icon-qianbaoqiandaiyue',
          'icon-apartment',
          'icon-piaoju1',
        ],
      },
    ],
  };
}
