module.exports = {
  RWS_USER_TYPE: '01',
  TA_USER_TYPE: '02',
  SUB_TA_USER_TYPE: '03',
  RWS_COMPANY: 'RWS',
  RWS_ORG: 'RWS',
  TA_TYPE: 'TA',
  SUB_TA_TYPE: 'SUB_TA',
  RWS_USER_PRIVILEGE: 'USER_MGR_RWS_USER_PRIVILEGE',
  MAIN_TA_PRIVILEGE: 'USER_MGR_MAIN_TA_PRIVILEGE',
  SUB_TA_PRIVILEGE: 'USER_MGR_SUB_TA_PRIVILEGE',
};
