export const FILTER_TYPE = {
  INPUT: 'INPUT',
  SELECT: 'SELECT',
  MULTIPLE_SELECT: 'MULTIPLE_SELECT',
  DATE_PICKER: 'DATE_PICKER',
  RANGE_PICKER: 'RANGE_PICKER',
};

export const SELECT_TYPE_LIST = [FILTER_TYPE.SELECT, FILTER_TYPE.MULTIPLE_SELECT];

export const EXTRA_FILTER_TYPE = {
  SELECT_CATEGORY_TYPE: `${FILTER_TYPE.SELECT}_categoryType`,
  MULTIPLE_SELECT_CUSTOMER_GROUP: `${FILTER_TYPE.MULTIPLE_SELECT}_customerGroup`,
  MULTIPLE_SELECT_THEME_PARK_CODE: `${FILTER_TYPE.MULTIPLE_SELECT}_themeParkCode`,
  MULTIPLE_SELECT_AGE_GROUP: `${FILTER_TYPE.MULTIPLE_SELECT}_ageGroup`,
  MULTIPLE_SELECT_ACCOUNT_MANAGER: `${FILTER_TYPE.MULTIPLE_SELECT}_accountManager`,
};
